version: 0.8.{build}
configuration:
- RelWithDebInfo
- Release
platform: x64
clone_depth: 1
before_build:
- ps: nuget restore
build:
  project: MeoAssistance.sln
  parallel: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - mistereo@hotmail.com
  subject: 'Build {{status}}: {{projectName}} {{buildVersion}}'
  message: 'Commit #{{commitId}} by {{commitAuthor}} on {{commitDate}}: {{commitMessage}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
on_failure:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))