name: dev-build-linux

on:
  push:
    branches-ignore:
      - master
    paths:
      - 'src/MeoAssistant/**'
      - '3rdparty/**'
      - 'include/**'
      - 'resource/**'
      - CMakeLists.txt
  pull_request:
    branches:
      - dev
    paths:
      - 'src/MeoAssistant/**'
      - '3rdparty/**'
      - 'include/**'
      - 'resource/**'
      - CMakeLists.txt
  workflow_dispatch:

jobs:
  linux-latest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install GCC-12
        run: |
          sudo apt update
          sudo apt install gcc-12 g++-12

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          remove_stale_cache: false

      - name: Download libraries
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ~
          gh release download --repo aa889788/build-opencv --pattern '*Linux.tar.gz'
          gh release download --repo aa889788/build-fastdeploy --pattern '*Linux.tar.gz'
          find . -maxdepth 1 -name '*.tar.gz' -exec tar -xvf '{}' \;

      - name: Build MAA
        env:
          CC: ccache gcc-12
          CXX: ccache g++-12
        run: |
          mkdir -p build
          cmake -B build \
              -DFASTDEPLOY_INSTALL_DIR=~/fastdeploy \
              -DOpenCV_DIR=~/opencv/lib/cmake/opencv4 \
              -DINSTALL_THIRD_LIBS=ON
          cmake --build build
          
          mkdir -p install
          cmake --install build --prefix install

      - run: |
          mkdir -p release
          cd install
          tar czvf $GITHUB_WORKSPACE/release/MaaAssistantArknights.tar.gz .

      - uses: actions/upload-artifact@v3
        with:
          name: MAA-linux
          path: release/*.tar.gz
