name: Release Note Distribution
on:
  workflow_dispatch:
  release:
    types: [edited]

jobs:
  mirrorchyan:
    name: Upload to MirrorChyan
    runs-on: macos-latest

    steps:
      - name: Upload release notes to MirrorChyan
        uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: MAA

          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
