name: Release Version Tagging

on:
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:
    inputs:
      tag:
        description: "Name of the tag to create for the release"
        type: string
        required: true

jobs:
  auto_tag_release:
    name: Tag Release
    if: github.event.pull_request.merged == true && (startsWith(github.event.pull_request.title, 'Release v') || startsWith(github.event.pull_request.title, 'release v')) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.MAARELEASE_RELEASE }}

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Determine tag name
        id: extract_tag
        run: |
          if ${{ github.event_name != 'workflow_dispatch' }}; then
            tag_name=$(echo "${{ github.event.pull_request.title }}" | sed -E 's/(Release|release)//' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
            echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
          else
            echo "tag_name=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          fi

      - name: Create and push release tag
        run: |
          git tag -a "${{ steps.extract_tag.outputs.tag_name }}" -m "${{ steps.extract_tag.outputs.tag_name }}" -f
          git push origin "${{ steps.extract_tag.outputs.tag_name }}"

      - name: Merge tag into dev and push
        run: |
          git switch dev
          git merge "${{ steps.extract_tag.outputs.tag_name }}"
          git push origin dev
