name: "Mark stale issues and pull requests"

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      # Completely disable stalling for PRs
      pull-requests: none
      contents: none
    steps:
      - name: Close inactive issues
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30 # Number of days of inactivity before marking as stale
          days-before-close: 3 # Number of days to wait after marking as stale before closing
          stale-issue-label: "stale"
          stale-issue-message: |
            "This issue has been inactive for a prolonged period and will be closed automatically in 3 days."
            "该问题已长时间处于闲置状态，3 天后将自动关闭。"
          exempt-issue-labels: "keep-open, MAA Team"
          # Completely disable stalling for PRs
          days-before-pr-stale: -1
          days-before-pr-close: -1

          debug-only: true
