name: Submit to Winget
on:
  release:
    types: [published]

jobs:
  submit:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install wingetcreate
        run: winget install wingetcreate

      - name: Update Winget Manifest
        run: 
          wingetcreate update MaaAssistantArknights.MaaAssistantArknights `
          --version ${{ env.VERSION }}
          --urls "https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v${{ env.VERSION }}/MAA-v${{ env.VERSION }}-win-x64.zip,https://github.com/MaaAssistantArknights/MaaAssistantArknights/releases/download/v${{ env.VERSION }}/MAA-v${{ env.VERSION }}-win-arm64.zip" `
          --token ${{ secrets.PAT_FOR_WINGET }} `
          --fork microsoft/winget-pkgs
